version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.css)
  mime_type: text/css
  static_files: static/
  upload: static/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: js/
  upload: js/(.*\.js)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: txt/
  upload: txt/(.*\.txt)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: xml/
  upload: xml/(.*\.xml)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: images/
  upload: images/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# index files
- url: /index.html
  static_files: index.html
  upload: index.html

# site root
- url: /*
  static_files: index.html
  upload: index.html
